# Connessione al Database
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Comportamento Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Ottimizzazione: Spegne l'OSIV per non sprecare risorse
spring.jpa.open-in-view=false