# =================================================================
# Configurazione Base PlayNode Mosquitto Broker
# =================================================================

# 1. Porta di ascolto principale per i microservizi (Spring Boot)
# Il prefisso 0.0.0.0 dice a Mosquitto di accettare connessioni da qualunque IP (quindi anche dagli altri container)
listener 1883 0.0.0.0

# 2. Porta per le connessioni WebSocket (utile se in futuro il frontend Web vorrà connettersi a MQTT)
listener 9001 0.0.0.0
protocol websockets

# 3. Sicurezza Temporanea (Sblocco per i test)
# Permette ai servizi di collegarsi senza inviare per forza username e password.
# NOTA: Dato che nel tuo game-service usi ${MQTT_USER}, Mosquitto accetterà comunque la connessione.
allow_anonymous true

# 4. Persistence (Salvataggio dei messaggi su disco in caso di riavvio)
persistence true
persistence_location /mosquitto/data/

# 5. Log di debug (fondamentali per vedere cosa fanno i tuoi giochi)
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information