# Per farlo funzionare da Intellij bisogna configurare prima le variabili d'ambiente di ogni microservizio:
#   Edit Configuration... -> Modify options -> Environment variable

spring.application.name=tournament-service
server.port=8083

spring.config.import=optional:file:./docker/.env,optional:file:../../docker/.env

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs