spring.application.name=game-service
server.port=8080


spring.datasource.url=jdbc:postgresql://${DB_HOST:playnode_postgres}:${DB_INTERNAL_PORT:5432}/${DB_NAME:playnode_db}
spring.datasource.username=${DB_USER:playnode_admin}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# --- CONFIGURAZIONI MQTT ---
mqtt.broker.url=tcp://192.168.1.15:1883
mqtt.client.id=game-service-publisher
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}