spring.application.name=game-service

# 1. Importa le variabili d'ambiente dal file .env
spring.config.import=optional:file:../../docker/.env

# 2. Connessione al Database
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 3. Comportamento Hibernate (usiamo none per non toccare init.sql)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Configurazione Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs