# Nome del nostro microservizio
spring.application.name=stats-service

# --- CONFIGURAZIONI MQTT ---
# Indirizzo del broker MQTT (usiamo localhost e la porta standard 1883)
mqtt.broker.url=tcp://localhost:1883
# Un ID univoco per questo servizio quando si connette al broker
mqtt.client.id=stats-service-client
# Il topic generale a cui vogliamo abbonarci (il simbolo # indica tutto ciò che segue)
mqtt.topic=locale/#