# Per farlo funzionare da Intellij bisogna configurare prima le variabili d'ambiente di ogni microservizio:
#   Edit Configuration... -> Modify options -> Environment variable

spring.application.name=stats-service
server.port=8082

spring.datasource.url=jdbc:postgresql://playnode_postgres:5432/PlayNode_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=stats-service-client
mqtt.topic=locale/#

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs